@startuml
!include style.iuml

title RX Operation $create

start
:Client ruft POST /Task/$create auf;
:FD prüft Rolle aus ACCESS_TOKEN;
if (Rolle zuässig?) then (ja)
else (nein)
  :HTTP 403;
  stop
endif

:FD validiert Parameters gegen CreateOperationDefinition;
if (Schema gültig?) then (ja)
else (nein)
  :HTTP 400;
  stop
endif

:FD übernimmt workflowType;
:FD erzeugt PrescriptionID, Task.id und AccessCode;
:FD setzt Task.status = draft;
:FD gibt Task zurück;
stop

@enduml
