@startuml
title E-Rezept-Abgabe zeitnah dokumentieren

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Dispensierdaten erfassen()
activate AVS

AVS -> FD: POST /Task/{id}/$dispense (Secret, Parameters)
activate FD
FD -> FD: Dispensierdaten plausibilisieren()
FD -> FD: Dispensierdaten speichern()
FD --> AVS: Status
deactivate FD

AVS --> MA: Status
deactivate AVS

@enduml
