@startuml
title Dispensierinformationen bereitstellen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Dispensierdaten erfassen()
activate AVS

AVS -> FD: POST /Task/{id}/$dispense (MedicationDispense)
activate FD
FD -> FD: Dispensierdaten prüfen()
FD -> FD: Dispensierdaten speichern()
FD --> AVS: Status
deactivate FD

AVS --> MA: Status
deactivate AVS

@enduml
