@startuml
title UC 4.9 - Nachricht durch Abgebenden loeschen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Nachricht loeschen()
activate AVS

AVS -> FD: DELETE /Communication/{id} ()
activate FD
FD -> FD: Nachricht löschen()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Nachricht lokal löschen()
AVS --> MA: Status
deactivate AVS

@enduml
