@startuml
title sd UC 3.9 - Dispensierinformationen durch Versicherte abrufen

actor Versicherter as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE : Dispensierinformationen abrufen()

FE -> FD : GET /Dispensierinformationen ()

activate FD
FD -> FD : Zugriffsprotokoll erstellen()
FD --> FE : {Dispensierinformationen,\nStatus, ...}
deactivate FD

FE --> V : Status
@enduml
