@startuml
title UC 4.2 - E-Rezept durch Abgebenden zurueckgeben

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "Identity Provider" as IDP
participant "E-Rezept Fachdienst" as FD

MA -> AVS: E-Rezept zurueckgeben()
activate AVS

opt kein gueltiger AuthN-Token
  ref over AVS, IDP: AuthN-Token anfordern
end

AVS -> FD: POST /Task/{id}/$reject (AuthN-Token, AccessCode, Secret)
activate FD
FD -> FD: Status auf "offen" setzen()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Token und Secret loeschen()
AVS --> MA: Status
deactivate AVS

@enduml
