@startuml
title UC 3.1 - E-Rezepte durch Versicherten abrufen

actor "Versicherter" as V
participant "FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

V -> FdV: E-Rezepte abrufen()
activate FdV

FdV -> FD: GET /Task ()
activate FD
FD -> FD: E-Rezepte nach Versicherten-ID ermitteln()
FD --> FdV: E-Rezepte, Status, Zeitpunkte, AccessCodes
deactivate FD

FdV --> V: Liste der E-Rezepte
deactivate FdV

@enduml
