@startuml
title E-Rezept erstellen

actor "Verordnender" as V
participant "Primaersystem" as PS
participant "Identity Provider" as IDP
participant "E-Rezept Fachdienst" as FD

V -> PS: Verordnung erfassen()
activate PS

PS -> PS: Verordnungsdaten erstellen()

opt kein gueltiger AuthN-Token
  ref over PS, IDP: AuthN-Token anfordern
end

PS -> FD: POST /Task/$create (AuthN-Token, Verordnungsdaten)
activate FD
FD -> FD: Verordnungsdaten pruefen()
FD -> FD: Task anlegen()
FD -> FD: AccessCode erzeugen()
FD --> PS: Task, AccessCode
deactivate FD

PS --> V: Task-ID, AccessCode
deactivate PS

@enduml
