@startuml 
title UC 3.13 - Einwilligungen durch den Versicherten einsehen

autonumber "<b>[0]"
actor "Versicherte" as Ver
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Ver -> FdV: Einwilligungen einsehen
FdV -> FD: GET /Consent()
FD --> FdV: :Consent Liste
FdV --> Ver: Anzeige

@enduml  