@startuml
title UC 4.6 - Nachrichten durch Abgebenden empfangen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "Identity Provider" as IDP
participant "E-Rezept Fachdienst" as FD

MA -> AVS: E-Rezept-Token empfangen()
activate AVS

alt Empfang ueber TI
  opt kein gueltiger AuthN-Token
    ref over AVS, IDP: AuthN-Token anfordern
  end
  AVS -> FD: GET /Communication?recipient=Telematik-ID (AuthN-Token)
  activate FD
  FD -> FD: Nachrichten ermitteln()
  FD --> AVS: E-Rezept-Token
  deactivate FD
else 2D-Code
  AVS -> AVS: 2D-Code scannen()
  AVS -> AVS: Token extrahieren()
end

AVS --> MA: Token verfuegbar
deactivate AVS

@enduml
