@startuml
title E-Rezept abschliessen oder zurückweisen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Abschluss oder Rückgabe anstossen()
activate AVS

alt Task schliessen
  AVS -> FD: POST /Task/{id}/$close (Quittung)
  activate FD
  FD -> FD: Quittung prüfen()
  FD -> FD: Task abschliessen()
  FD --> AVS: Status
  deactivate FD
else Task zurückweisen
  AVS -> FD: POST /Task/{id}/$reject ()
  activate FD
  FD -> FD: Status Task auf ready setzen()
  FD --> AVS: Status
  deactivate FD
end

AVS --> MA: Status
deactivate AVS

@enduml
