@startuml
title UC 4.1 - E-Rezept durch Abgebenden abrufen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD
participant "Konnektor" as K

MA -> AVS: E-Rezept abrufen()
activate AVS
AVS -> AVS: Rezept-ID und AccessCode aus Token ermitteln()

AVS -> FD: POST /Task/{id}/$accept (AccessCode)
activate FD
FD -> FD: AccessCode prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Status auf "in-progress" setzen()
FD -> FD: Geheimnis erzeugen()
FD --> AVS: Task, Binary, Geheimnis
deactivate FD

opt
AVS -> K: QES prüfen(Binary)
activate K
K --> AVS: Ergebnis
deactivate K
end

AVS --> MA: Status und Verordnungsdaten
deactivate AVS

@enduml
