@startuml
title UC 4.2 - E-Rezept durch Abgebenden zurückgeben

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: E-Rezept zurückgeben()
activate AVS

AVS -> FD: POST /Task/{id}/$reject (Secret)
activate FD
FD -> FD: Status auf "ready" setzen()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Token und Secret löschen()
AVS --> MA: Status
deactivate AVS

@enduml
