@startuml
title UC 3.8 - Nachricht durch Versicherten loeschen

actor "Versicherter" as V
participant "FdV" as FdV
participant "Identity Provider" as IDP
participant "E-Rezept Fachdienst" as FD

V -> FdV: Nachricht loeschen()
activate FdV

opt kein gueltiger AuthN-Token
  ref over FdV, IDP: AuthN-Token anfordern
end

FdV -> FD: DELETE /Communication/{id} (AuthN-Token)
activate FD
FD -> FD: Nachricht loeschen()
FD --> FdV: Status (ggf. Warning)
deactivate FD

FdV -> FdV: Nachricht lokal loeschen()
FdV --> V: Status
deactivate FdV

@enduml
