@startuml
title UC 3.8 - Nachricht durch Versicherten löschen

actor "Versicherter" as V
participant "FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

V -> FdV: Nachricht löschen()
activate FdV

FdV -> FD: DELETE /Communication/{id} ()
activate FD
FD -> FD: Nachricht löschen()
FD --> FdV: Status
deactivate FD

FdV -> FdV: Nachricht lokal löschen()
FdV --> V: Status
deactivate FdV

@enduml
