@startuml
title Uebertragen an den ePA MedicationService

participant "E-Rezept Fachdienst" as FD
participant "ePA MedicationService" as EPA

FD -> FD: Ereignis nach $activate/$dispense/$close/$abort
FD -> EPA: Uebertragung von Medikationsdaten
activate EPA
EPA --> FD: Status
deactivate EPA

@enduml
