Logical: ERP_TPrescription_CarbonCopy_Logical
Id: erp-tprescription-carbon-copy-logical
Title: "Logisches Modell digitaler Durchschlag E-T-Rezept"
Description: "Logical Model zur Abbildung der im digitalen Durchschlag E-T-Rezept erforderlichen fachlichen Informationen."
// TI-Flow-26_2 KBV_05, KBV_07, KBV_09, KBV_10
* datumSignatur 1..1 instant "Zeitpunkt der Signatur"
  * ^comment = "Datenquelle: QES des Verordnungsdatensatzes. Dieses Datum wird aus der QES Signatur 1.2.840.113549.1.9.5 signingTime herangezogen und muss in ein FHIR Instant Datenformat überführt werden."
* rezeptID 1..1 Identifier "E-Rezept-ID"
  * ^comment = "Datenquelle: Task"

* AngabenVerordnung 1..1 BackboneElement "Angaben zum verordneten Medikament"
  * bezeichnung 0..1 CodeableConcept "Bezeichnung des verordneten Arzneimittels. Ein T-Arzneimittel kann in Form aller vier Verordnungstypen (PZN-, Freitext-, Strukturierte Wirkstoff-, Strukturierte Rezeptur-Verordnung) verordnet werden."
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * wirkstaerke 0..1 Ratio "Wirkstärke (verordnetes Arzneimittel)"
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * darreichungsform[x] 0..1 string or Coding "Darreichungsform (verordnetes Arzneimittel)"
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * menge 0..1 Ratio "Menge (verordnetes Arzneimittel)"
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * dosierung 0..1 Dosage "Dosierung (verordnetes Arzneimittel). Das Profil entspricht DosageDgMp des [IG DE Medication](https://ig.fhir.de/igs/medication/1.0.7/)"
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * reichdauer 1..1 Duration "Reichdauer (verordnetes Arzneimittel)"
    * ^comment = "Datenquelle: Verordnungsdatensatz"
  * TRezeptBestaetigungen 1..1 BackboneElement "Bestätigungen des Arztes nach §3a Abs. 2, 5 AMVV"
    * bestaetigungSicherheitsmassnahmen 1..1 boolean "Bestätigung Sicherheitsmaßnahmen (T-Rezept)"
      * ^comment = "Datenquelle: Verordnungsdatensatz"
    * aushaendigungInformationsmaterialien 1..1 boolean "Aushändigung Informationsmaterialien (T-Rezept)"
      * ^comment = "Datenquelle: Verordnungsdatensatz"
    * offLabelUse 1..1 boolean "Behandlung außerhalb der zugelassenen Anwendungsgebiete (Off-Label)"
      * ^comment = "Datenquelle: Verordnungsdatensatz"
    * gebaerfaehigeFrau 1..1 boolean "Verschreibung für gebärfähige Frau"
      * ^comment = "Datenquelle: Verordnungsdatensatz"
    * erklaerungSachkenntnis 1..1 boolean "Bestätigung der Sachkenntnis"
      * ^comment = "Datenquelle: Verordnungsdatensatz"

* AngabenDispensierung 1..1 BackboneElement "Angaben zum abgegeben Medikament"
  * bezeichnung 1..1 CodeableConcept "Bezeichnung Fertigarzneimittel/Wirkstoff ODER Rezeptur (abgegeben). Diese Angabe kann als Freitext oder strukturiert vorliegen."
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * wirkstaerke 0..1 Ratio "Wirkstärke (abgegebenes Arzneimittel)"
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * darreichungsform 0..1 string "Darreichungsform (abgegebenes Arzneimittel)"
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * menge 0..1 Ratio "Menge (abgegebenes Arzneimittel)"
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * dosierung 0..1 Dosage "Dosierung (abgegebenes Arzneimittel)"
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * datumAbgabe 1..1 date "Datum der Abgabe im Format YYYY-MM-DD"
    * ^comment = "Datenquelle: Dispensierdatensatz"

* AngabenAbgebendeApotheke 1..1 BackboneElement "Angaben zur Abgebenden Apotheke"
  * telematikID 1..1 string "Telematik-ID der Apotheke"
    * ^comment = "Datenquelle: Dispensierdatensatz"
  * name 0..1 string "Name der Apotheke"
    * ^comment = "Datenquelle: FHIR-VZD"
  * anschrift 0..1 Address "Anschrift der Apotheke"
    * ^comment = "Datenquelle: FHIR-VZD"
  * telefonnummer 0..1 ContactPoint "Telefonnummer der Apotheke"
    * ^comment = "Datenquelle: FHIR-VZD"