install:
  - firely_terminal
  - sushi
  - igpub
  - requirements
  - publishtools
  - igtools
deploy:
  env:
    dev: gematik_gemspec_fhir_dev-0
    prod: gematik_gemspec_fhir_prod-0
build:
  pipeline:
    - shell: ../../scripts/install-ig-packages.sh ./fhir-ig-installer.conf
    - shell: ./scripts/pre-build.sh
    - requirements
    - shell: reqtools polarion ./input/content
    - sushi
    - requirements
    - igpub
    - igpub_qa
    - shell: ./scripts/post-build.sh