@startuml
title Einwilligung zum Speichern der Abrechnungsinformationen durch den Versicherten widerrufen

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Einwilligung widerrufen()
activate FE

FE -> V: Bestätigung zum Widerruf anfordern()

FE -> FD: DELETE /Consent?category=CHARGCONS ()
activate FD

FD -> FD: Einwilligung prüfen()
FD -> FD: Einwilligung löschen()
FD -> FD: Löschen Einwilligung protokollieren()
FD -> FD: Abrechnungsinformationen löschen()
FD -> FD: Löschen Abrechnungsinformationen protokollieren()

FD --> FE: status
deactivate FD

FE --> V: status
deactivate FE

@enduml
