@startuml
title Abrechnungsinformation durch den Versicherten löschen

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Abrechnungsinformationen löschen()
activate FE

FE -> V: Bestätigung zum Löschen anfordern()
FE -> FE: Abrechnungsinformation auswählen()
FE -> FE: PrescriptionID zu Abrechnungsinformation bestimmen()

FE -> FD: DELETE /ChargeItem/{PrescriptionID} ()
activate FD

FD -> FD: Abrechnungsinformation löschen()
FD -> FD: Löschvorgang protokollieren()

FD --> FE: status
deactivate FD

FE --> V: status
deactivate FE

@enduml
