@startuml
title Einwilligungen durch Versicherten einsehen

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Einwilligungen einsehen()
activate FE

FE -> FD: GET /Consent ()
activate FD

FD --> FE: Consent Liste
deactivate FD

FE --> V: Consent
deactivate FE

@enduml
