@startuml
title Einwilligung zum Speichern der Abrechnungsinformationen durch den Versicherten erteilen

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Einwilligung erteilen()
activate FE

FE -> FD: POST /Consent()
activate FD

FD -> FD: Einwilligung speichern()
FD -> FD: Datenzugriff protokollieren()

FD --> FE: Consent
deactivate FD

FE --> V: Status()
deactivate FE

@enduml
