@startuml
title Abrechnungsinformation durch Abgebenden abrufen

actor "Mitarbeiter LEI" as MA
participant "Primärsystem\nabgebende LEI" as PS
participant "TI-Flow-Fachdienst" as FD

MA -> PS: Abrechnungsinformation abrufen()
activate PS

PS -> FD: GET /ChargeItem/{PrescriptionID}(AccessCode zum Ändern)
activate FD

FD -> FD: AccessCode zum Ändern prüfen()
FD -> FD: Telematik-ID prüfen()
FD -> FD: Datenzugriff protokollieren()

FD --> PS: ChargeItem (Verordnung, PKV-Abgabedatensatz)
deactivate FD

PS --> MA: ChargeItem (Verordnung, PKV-Abgabedatensatz)
deactivate PS

@enduml
