@startuml
title Abrechnungsinformationen durch den Versicherten abrufen

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Abrechnungsinformationen abrufen()
activate FE

opt dem FdV sind keine Abrechnungsinformationen bekannt
  FE -> FD: GET /ChargeItem ()
  activate FD
  FD --> FE: ChargeItem Liste
  deactivate FD
  FE --> V: Liste aller Abrechnungsinformationen des Versicherten
end

V -> FE: Abrechnungsinformation auswählen()
FE -> FD: GET /ChargeItem/{PrescriptionID} ()
activate FD

FD -> FD: Datensätze signieren()
FD -> FD: Datenzugriff protokollieren()

FD --> FE: ChargeItem
deactivate FD

FE --> V: Abrechnungsinformation
deactivate FE

@enduml
