@startuml
title Abrechnungsinformation durch den Versicherten markieren

actor "Versicherter" as V
participant "Frontend des\nVersicherten" as FE
participant "TI-Flow-Fachdienst" as FD

V -> FE: Abrechnungsinformation markieren()
activate FE

FE -> FE: Markierungen auswählen()
FE -> FE: PrescriptionID bestimmen()

FE -> FD: PATCH /ChargeItem/{PrescriptionID}()
activate FD

FD -> FD: Markierung speichern()
FD -> FD: Datenzugriff protokollieren()

FD --> FE: status
deactivate FD

FE --> V: status
deactivate FE

@enduml
