@startuml
title UC 3.3 - Nachricht durch Versicherten übermitteln

actor "Versicherter/Vertreter" as V
participant "FdV" as FdV
participant "Identity Provider" as IDP
participant "Verzeichnisdienst" as VZD
participant "E-Rezept-Fachdienst" as FD

V -> FdV: Nachricht mit Token senden()
activate FdV

alt Versand über TI
  opt kein gültiger AuthN-Token
    ref over FdV, IDP: AuthN-Token anfordern
  end
  FdV -> VZD: Apotheke suchen()
  VZD --> FdV: Empfängerdaten
  FdV -> FD: POST /Communication (AuthN-Token, Token, Payload)
  activate FD
  FD -> FD: Nachricht speichern()
  FD --> FdV: Status
  deactivate FD
else 2D-Code
  FdV -> FdV: Token als 2D-Code erzeugen()
  FdV --> V: 2D-Code anzeigen/ausdrucken
end

FdV --> V: Bestätigung
deactivate FdV

@enduml
