ValueSet: TIFLOWChargeItemOperationOutcomeDetailsVS
Id: tiflow-chargeitem-operation-outcome-details-vs
Title: "TIFLOW ChargeItem Operation Outcome Details VS"
Description: "Abrechnungsinformationen-spezifische Codes, die im Rahmen des TIFlow in den OperationOutcomes.details angegeben werden können"
* insert Meta-VS
* include codes from system TIFLOWChargeItemOperationOutcomeDetailsCS
* include $tiflow-core-oo-cs#TIFLOW_AUTH_ROLE_NOT_ALLOWED "Access role not allowed"
* include $tiflow-core-oo-cs#SVC_IDENTITY_MISMATCH "Identity mismatch: Access token or x-insurantid header does not match FHIR data (Telematik-ID / KVNR)"
* include TIOperationOutcomeDetailsCS#SVC_VALIDATION_FAILED "FHIR Profile Validation Failed"
* include $tiflow-core-oo-cs#TIFLOW_CONSENT_ALREADY_EXISTS "Consent already exists"
* include $tiflow-core-oo-cs#TIFLOW_CONSENT_CATEGORY_REQUIRED "Consent category required"
* include $tiflow-core-oo-cs#TIFLOW_CONSENT_CATEGORY_INVALID "Consent category invalid"
* include $tiflow-core-oo-cs#TIFLOW_ACCESSCODE_MISMATCH "Access code mismatch"
* include $tiflow-core-oo-cs#TIFLOW_TASK_REQUIRED "Task required"
* include $tiflow-core-oo-cs#TIFLOW_TASK_NOT_FOUND "Task not found"
* include $tiflow-core-oo-cs#TIFLOW_SECRET_MISMATCH "Task secret mismatch"
* include $tiflow-core-oo-cs#TIFLOW_CONSENT_REQUIRED "Consent required"
* include $tiflow-core-oo-cs#TIFLOW_OCSP_BACKEND_ERROR "Invalid OCSP response"
* include $tiflow-core-oo-cs#TIFLOW_MESSAGE_TO_SELF "Message to self not allowed"
* include $tiflow-core-oo-cs#TIFLOW_COMMUNICATION_PAYLOAD_INVALID "Communication payload invalid"
* include $tiflow-core-oo-cs#TIFLOW_INSURANT_NOT_ELIGIBLE "Insurant not eligible"
* include $tiflow-core-oo-cs#TIFLOW_RECIPIENT_INVALID "Recipient invalid"
* include $tiflow-core-oo-cs#TIFLOW_TASK_STATUS_MISMATCH "Task status mismatch"
* include $tiflow-core-oo-cs#TIFLOW_TASK_EXPIRED "Task expired"
* include $tiflow-core-oo-cs#TIFLOW_MVO_NOT_VALID_YET "MVO not valid yet"
