@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Standardablauf: Leistungsentscheidung nach Zuweisung (ohne Korrektur)

$state_init(init)
$state_open(open)
$state_assigned(assigned)
$state_assigned_decided(assigned_decided)
$state_completed(completed)
$state_cancelled(deleted)
$state_review_from_assigned(review)


[*] -> init

init -> open : <color:black><back:Lime> 1
open -> assigned : <color:black><back:Lime> 2

assigned -> review : <color:black><back:Salmon> AP3


review -> assigned_decided : <color:black><back:Salmon> AP4

' review --> subreview_requested

' subreview_requested --> subreview_progress 
' subreview_progress --> subreview_completed
' subreview_completed --> assigned_decided : <color:black><back:Salmon> AP4

assigned_decided -[dashed]>  completed : <color:black><back:DeepSkyBlue> AA2

completed -> deleted : <color:black><back:yellow> ML3
completed -[dashed]> deleted : <color:black><back:Lavender> AL2

deleted -> [*]

@enduml
