@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

' title HKP Workflow - Gesamtübersicht

$state_init(init)
$state_open(open)
$state_open_approved(open_approved)
$state_assigned(assigned)
$state_review_from_open(open_review)
$state_review_from_assigned(assigned_review)

$state_assigned_approved(assigned_approved)
$state_completed(completed)
$state_cancelled(deleted)


$state_correction(correction)
$state_correction_open(correction_open)


[*] -d-> init

init -d-> open : <color:black><back:Lime> 1
open -d-> assigned : <color:black><back:Lime> 2
assigned -d-> open : <color:black><back:Lime> 3

assigned -d-> assigned_review : <color:black><back:Salmon> AP3

assigned -d-> correction : <color:black><back:DarkOrange> K1
assigned <-d- correction : <color:black><back:DarkOrange> K2
assigned <-d- correction : <color:black><back:DarkOrange> K3

correction <-d- assigned_review : <color:black><back:DarkOrange> K4
correction -d-> assigned_review : <color:black><back:DarkOrange> K5
correction -d-> assigned_review : <color:black><back:DarkOrange> K6

' correction_open <-u- open_review : <color:black><back:DarkOrange> K4
' correction_open -u-> open_review : <color:black><back:DarkOrange> K5
' correction_open -d-> open_review : <color:black><back:DarkOrange> K6
correction_open <-d- open_review : <color:black><back:DarkOrange> K4
correction_open -l-> open_review : <color:black><back:DarkOrange> K5
correction_open -l-> open_review : <color:black><back:DarkOrange> K6



assigned_review -d-> assigned_approved : <color:black><back:Salmon> AP4

open -l-> open_review : <color:black><back:Salmon> AP1

open -[dashed]->  completed : <color:black><back:DeepSkyBlue> AA1
' open -d-> completed : <color:black><back:Lime> 4

open_review -r-> open_approved : <color:black><back:Salmon> AP2
open_approved -[dashed]->  completed : <color:black><back:DeepSkyBlue> AA1
' open_approved -d-> completed : <color:black><back:Lime> 4

assigned_review -[dashed]-> deleted : <color:black><back:Lavender> AL3
open_review -[dashed]-> deleted : <color:black><back:Lavender> AL3

assigned -[dashed]->  completed : <color:black><back:DeepSkyBlue> AA2
assigned_approved -d-> completed : <color:black><back:DeepSkyBlue> AA2

init -d-> deleted : <color:black><back:yellow> ML1
init -[dashed]-> deleted : <color:black><back:Lavender> AL1

open -d-> deleted : <color:black><back:yellow> ML2

completed -d-> deleted : <color:black><back:yellow> ML3
completed -[dashed]-> deleted : <color:black><back:Lavender> AL2

deleted -d-> [*]

@enduml
