@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Korrekturprozess durch Kostenträger (K4-K5)

$state_init(init)
$state_open(open)
$state_assigned(assigned)
$state_assigned_reviewed(assigned_reviewed)
$state_completed(completed)
$state_review_from_assigned(review)
$state_correction(correction_review)



[*] -> init

init -> open : <color:black><back:Lime> 1
open -> assigned : <color:black><back:Lime> 2

assigned -> review : <color:black><back:Salmon> AP3

review --> correction_review : <color:black><back:DarkOrange> K4
correction_review -> review : <color:black><back:DarkOrange> K5

review -> assigned_reviewed : <color:black><back:Salmon> AP4
assigned_reviewed -> completed : <color:black><back:DeepSkyBlue> AA2

completed -> [*]

@enduml