@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

' title HKP Workflow - Korrekturprozess

$state_assigned_approved(assigned_approved)

$state_assigned(assigned)
$state_review_from_assigned(review)
' $state_correction(correction)

' $state_review_correction(correction_review)
$state_correction(correction)

assigned --> correction : <color:black><back:DarkOrange> K1
assigned <-- correction : <color:black><back:DarkOrange> K2
assigned <-- correction : <color:black><back:DarkOrange> K3

correction <-- review : <color:black><back:DarkOrange> K4
correction --> review : <color:black><back:DarkOrange> K5
correction --> review : <color:black><back:DarkOrange> K6


review --> assigned_approved : <color:black><back:Salmon> AP4

'TODO: Frage hier AP3 noch abzudecken?

@enduml
