@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

$state_open(open)
$state_open_approved(open_approved)
$state_assigned(assigned)
$state_assigned_approved(assigned_approved)
$state_review_from_assigned(review)
$state_review_correction(correction)

state "Sub-Workflow Korrektur" as correction_workflow {
    $state_correction_requested(correction_requested, "Kostenträger", "verordnenden Praxis / Pflegedienst")
    $state_correction_cancelled(correction_cancelled, "Kostenträger", "verordnenden Praxis / Pflegedienst")
    $state_correction_rejected(correction_rejected, "Kostenträger", "verordnenden Praxis / Pflegedienst")
    $state_correction_in_progress(correction_in_progress, "Kostenträger", "verordnenden Praxis / Pflegedienst")
    $state_correction_completed(correction_completed, "Kostenträger", "verordnenden Praxis / Pflegedienst")
}

open -r-> review : <color:black><back:Salmon> AP1
review -r-> open_approved : <color:black><back:Salmon> AP2

assigned -r-> review : <color:black><back:Salmon> AP3
review -r-> assigned_approved : <color:black><back:Salmon> AP4

review -d-> correction : <color:black><back:Khaki> K4
' correction -u-> review : <color:black><back:Khaki> K6
correction -d-> correction_requested : <color:black><back:Khaki><size:12> K4 <<invoke>>

correction_requested  -r-> correction_cancelled
correction_requested -d-> correction_in_progress
correction_in_progress -[dashed]u-> correction_requested
correction_in_progress -d-> correction_completed
correction_in_progress  -d-> correction_rejected

correction_completed -l-> correction : <color:black><back:Khaki><size:16> K5
correction_rejected -l-> correction : <color:black><back:Khaki><size:16> K6
correction_cancelled -l-> correction : <color:black><back:Khaki><size:16> K6


correction -l-> review : <color:black><back:Khaki> K5
correction -l-> review : <color:black><back:Khaki> K6



@enduml

