@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Korrekturprozess durch Pflegedienst (K1-K2)

$state_init(init)
$state_open(open)
$state_assigned(assigned)
$state_assigned_approved(assigned_approved)
$state_completed(completed)
$state_review_from_open(review)
$state_correction(correction_assigned)

[*] -> init

init -> open : <color:black><back:Lime> 1
open -> assigned : <color:black><back:Lime> 2

assigned -d-> correction_assigned : <color:black><back:Khaki> K1
correction_assigned -u-> assigned : <color:black><back:Khaki> K2

assigned -> review : <color:black><back:Salmon> AP3
review -> assigned_approved : <color:black><back:Salmon> AP4

assigned_approved -> completed : <color:black><back:DeepSkyBlue> AA2

completed -> [*]

@enduml
