@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title HKP Workflow - Korrekturprozess

$state_assigned_decided(assigned_decided)

$state_assigned(assigned)
$state_review(review)
$state_correction(correction)

assigned --> correction : <color:black><back:Khaki> K1
assigned <-- correction : <color:black><back:Khaki> K2
assigned <-- correction : <color:black><back:Khaki> K3

correction <-- review : <color:black><back:Khaki> K4
correction --> review : <color:black><back:Khaki> K5
correction --> review : <color:black><back:Khaki> K6


review --> assigned_decided : <color:black><back:Salmon> AP4

'TODO: Frage hier AP3 noch abzudecken?

@enduml
