@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Korrekturprozess mit Rücknahme (K3-K6)

$state_init(init)
$state_open(open)
$state_assigned(assigned)
$state_assigned_decided(assigned_decided)
$state_completed(completed)
$state_review(review)

$state_review_correction(correction_review)
$state_assigned_correction(correction_assigned)

[*] -> init

init -> open : <color:black><back:Lime> 1
open -> assigned : <color:black><back:Lime> 2

assigned --> correction_assigned : <color:black><back:Khaki> K1
correction_assigned -> assigned : <color:black><back:Khaki> K3

assigned -> review : <color:black><back:Salmon> AP3

review --> correction_review : <color:black><back:Khaki> K4
correction_review -> review : <color:black><back:Khaki> K6

review -> assigned_decided : <color:black><back:Salmon> AP4
assigned_decided -> completed : <color:black><back:DeepSkyBlue> AA2

completed -> [*]

@enduml
