@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Korrekturprozess  (K3-K6)

$state_init(init)
$state_open(open)
$state_assigned(assigned)
$state_assigned_approved(assigned_approved)
$state_completed(completed)
$state_review_from_assigned(review)

' $state_review_correction(correction_review)
$state_assigned_correction(correction_assigned)

[*] -> init

init -> open : <color:black><back:Lime> 1
open -> assigned : <color:black><back:Lime> 2

assigned -> correction_assigned : <color:black><back:Khaki> K1
correction_assigned -> assigned : <color:black><back:Khaki> K3

assigned -u-> review : <color:black><back:Salmon> AP3

review -> correction_assigned : <color:black><back:Khaki> K4
correction_assigned -> review : <color:black><back:Khaki> K6

review -> assigned_approved : <color:black><back:Salmon> AP4
assigned_approved -> completed : <color:black><back:DeepSkyBlue> AA2

completed -> [*]

@enduml
