@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

' title Antragsprüfung vor Zuweisung / Kostenerstattung

$state_init(init)
$state_open(open)
$state_completed(completed)
$state_cancelled(deleted)
$state_review_from_open(review)
$state_open_approved(open_approved)


[*] -> init

init -> open : <color:black><back:Lime> 1
open -> review : <color:black><back:Salmon> AP1
review -> open_approved : <color:black><back:Salmon> AP2

open_approved -[dashed]>  completed : <color:black><back:DeepSkyBlue> AA1
open_approved -> completed : <color:black><back:Lime> 4

completed -> deleted : <color:black><back:yellow> ML3
completed -[dashed]> deleted : <color:black><back:Lavender> AL2

deleted -> [*]

@enduml
