@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Löschen vor Veröffentlichung

$state_init(init)
$state_cancelled(deleted)


[*] -> init

init -> deleted : <color:black><back:yellow> ML1
init -[dashed]> deleted : <color:black><back:Lavender> AL1

deleted -> [*]

@enduml
