@startuml

!include ./utils/style.iuml
!include ./utils/states.iuml
hide empty description

title Automatische Löschung während der Antragsprüfung vor Zuweisung

$state_init(init)
$state_open(open)
$state_cancelled(deleted)
$state_review(review)



[*] -> init

init -> open : <color:black><back:Lime> 1
open -> review : <color:black><back:Salmon> AP1
review -[dashed]> deleted : <color:black><back:Lavender> AL3


deleted -> [*]

@enduml
