@startuml
title Zugriffsberechtigung durch den Versicherten einsehen

autonumber "<b>[0]"
actor Versicherte as Ver
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Ver -> FdV : Zugriffsberechtigung einsehen

FdV -> FD : Zugriffsberechtigung abfragen
FD --> FdV : Zugriffscode,\nZugriffscode gültig bis,\nLändercode

FdV --> Ver : Anzeige

@enduml