@startuml
title E-Rezept durch den Versicherten markieren

autonumber "<b>[0]"
actor Versicherte as Ver
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Ver -> FdV : E-Rezept auswählen
Ver -> FdV : Markierung auswählen/abwählen

FdV -> FD : PATCH /Task/{Task-ID}()
FD -> FD : Markierung speichern
FD -> FD : Datenzugriff protokollieren
FD --> FdV : Status

FdV --> Versicherte : Status anzeigen

@enduml