@startuml
title Zugriffsberechtigung durch Versicherten löschen

autonumber "<b>[0]"
actor Versicherte
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Versicherte -> FdV : Zugriffsberechtigung löschen

FdV -> FD : Zugriffscode löschen(KVNR)
FD -> FD : Zugriffscode für KVNR löschen
FD --> FdV : Status
FdV -> FdV : Zugriffscode löschen
FdV --> Versicherte : Status anzeigen

@enduml