@startuml
title UC Demographische Daten eines Versicherten abrufen

actor Versicherte
actor "LE-EU" as LEEU
participant "eHDSI / NCPeH-FD\nDeutschland" as NCP
participant "E-Rezept-Fachdienst" as FD

Versicherte -> LEEU : [1] Zugriffscode und KVNR übergeben
LEEU -> Versicherte : [2] Datenschutzerklärung

LEEU -> NCP : [3] Abfrage demographischer Versichertendaten
NCP -> NCP : [4] Prüfung Permission bzw. Rolle

NCP -> FD : [5] POST /$get-eu-prescriptions\n{AuthN-Token, KVNR, Zugriffscode,\nlaendercode, practitionerName,\npractitionerRole, pointOfCare,\nhealthcare-facility-type,\nlatest, requesttype}

FD -> FD : [6] Prüfung Einwilligung für KVNR
FD -> FD : [7] Prüfung Zugriffscode für KVNR\n(KVNR, Zugriffscode, laendercode,\naktueller Zeitpunkt)
FD -> FD : [8] aktuellsten einlösbare Task\nfür KVNR bestimmen
FD -> FD : [9] Zugriff protokollieren\n(KVNR, practitionerName,\npractitionerRole, pointOfCare,\nhealthcare-facility-type,\nrequesttype)

FD --> NCP : [10] Bundle von Verordnungen\n(max. eine Verordnung)
NCP -> NCP : [11] Transformierung und Transkodierung
NCP --> LEEU : [12] demographische Daten

@enduml