@startuml
title Zugriffsberechtigung durch Versicherten löschen

actor Versicherte
participant "E-Rezept-FdV" as FdV
participant "E-Rezept-Fachdienst" as FD
participant "Identity Provider" as IdP

Versicherte -> FdV : [1] Zugriffsberechtigung löschen

opt
  ref over FdV, IdP : [2] UC5.1 - AuthN-Token durch Versicherten anfordern
  FdV -> IdP : [2] UC5.1 - AuthN-Token durch Versicherten anfordern
end

FdV -> FD : [3] Zugriffscode löschen\n{AuthN-Token, KVNR}
FD -> FD : [4] Zugriffscode für KVNR löschen
FD --> FdV : [5] Status
FdV -> FdV : [6] Zugriffscode löschen
FdV --> Versicherte : [7] Status anzeigen

@enduml