@startuml
title UC Liste ausgewählter E-Rezepte eines Versicherten abrufen

autonumber "<b>[0]"
actor Versicherte as Ver
actor "LE-EU" as LEEU
participant "eHDSI / NCPeH-FD\nDeutschland" as NCP
participant "TI-Flow-Fachdienst" as FD

Ver -> LEEU : Abstimmung zu einzulösenden E-Rezepten
LEEU -> NCP : Abfrage Liste ausgewählter E-Rezepte

NCP -> NCP : Prüfung Behandlungsverhältnis\nLE-EU und Versicherter
NCP -> NCP : Prüfung Permission bzw. Rolle

NCP -> FD : POST /$get-eu-prescriptions\n{AuthN-Token, KVNR, Zugriffscode,\nListe von Task-IDs, laendercode,\npractitionerName, practitionerRole,\npointOfCare, healthcare-facility-type,\nrequesttype}

FD -> FD : Prüfung Einwilligung für KVNR
FD -> FD : Prüfung Zugriffscode für KVNR\n(KVNR, Zugriffscode, laendercode,\naktueller Zeitpunkt)
FD -> FD : Tasks zu Liste von Task-IDs bestimmen
FD -> FD : Zuordnung zu Tasks zu KVNR prüfen
FD -> FD : Einlösbarkeit der Tasks prüfen
FD -> FD : ggf. E-Rezept-Status "in progress" setzen
FD -> FD : Zugriff protokollieren\n(KVNR, practitionerName,\npractitionerRole, pointOfCare,\nhealthcare-facility-type,\nrequesttype)

FD --> NCP : Bundle von Verordnungen
NCP -> NCP : Transformierung und Transkodierung
NCP --> LEEU : Liste von ePrescriptions

@enduml