@startuml 
title UC 3.15 - Einwilligung durch den Versicherten widerrufen

autonumber "<b>[0]"
actor "Versicherte" as Ver
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Ver -> FdV: Einwilligung widerrufen
FdV -> FD: DELETE /Consent/?category()
FD -> FD: Einwilligung prüfen
FD -> FD: Einwilligung löschen
FD -> FD: Datenzugriff protokollieren
FD -> FD: optional: Löschen relevanter Daten
FD --> FdV: :Status
FdV --> Ver: Status

@enduml  