@startuml
title UC 2.3 - Verordnung einstellen

actor "Arzt" as Arzt
participant "Primärsystem" as PS
participant "TI-Flow-Fachdienst" as FD

Arzt -> PS: Verordnung zum Einstellen auswählen()
activate PS

PS -> FD: POST /hkp/fhir/task/{id}/$activate (AccessCode_state, QES-Bundle)
activate FD
FD -> FD: AccessCode_state prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Signatur und Daten prüfen()
FD -> FD: Status auf "ready" setzen()
FD -> FD: Business-Status auf "open" setzen()
FD --> PS: Status, Verordnung aktualisiert
deactivate FD

PS -> PS: Verordnungstoken erstellen()
PS --> Arzt: Verordnung eingestellt
deactivate PS

@enduml