@startuml
title UC 2.1 - Verordnung erzeugen

actor "Arzt" as Arzt
participant "Primärsystem" as PS
participant "TI-Flow-Fachdienst" as FD
participant "Konnektor" as K

Arzt -> PS: Verordnungsdatensatz auswählen()
activate PS

PS -> FD: POST /hkp/fhir/task/$create (Flowtype)
activate FD
FD -> FD: Task erzeugen()
FD -> FD: Verordnungs-ID erzeugen()
FD -> FD: AccessCode_state erzeugen()
FD -> FD: AccessCode_read erzeugen()
FD -> FD: Status auf "draft" setzen()
FD -> FD: Business-Status auf "initialized" setzen()
FD --> PS: Task, Verordnungs-ID, AccessCode_state, AccessCode_read
deactivate FD

PS -> PS: Verordnungs-ID im Verordnungsdatensatz einfügen()

ref over PS, K: Verordnungdatensatz signieren

PS -> PS: AccessCode_state speichern()
PS --> Arzt: Signierte Verordnung
deactivate PS

@enduml