@startuml
title UC 6.2 - Verordnung durch Abgebenden zurückgeben

actor "Mitarbeiter des Pflegedienstes" as MA
participant "Primärsystem" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Verordnung zurückgeben()
activate AVS

AVS -> FD: POST /hkp/fhir/task/{id}/$reject (Secret)
activate FD
FD -> FD: Secret prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Status auf "ready" setzen()
FD -> FD: Business-Status auf "open" setzen()
FD -> FD: Datenzugriff protokollieren()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Token und Secret löschen()
AVS --> MA: Status
deactivate AVS

@enduml