@startuml
title UC 6.x - HKP Verordnung durch Pflegedienst unverbindlich einsehen

actor "Mitarbeiter" as MA
participant "Primärsystem" as PS
participant "T_Flow-Fachdienst" as FD

MA -> PS: Verordnung abrufen()
activate PS
PS -> PS: Verordnungs-ID und AccessCode_read aus Token ermitteln()

PS -> FD: GET /hkp/fhir/task/{id}/$read (AccessCode_read)
activate FD
FD -> FD: AccessCode_read prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Datenzugriff protokollieren()
FD --> PS: Task, Binary
deactivate FD

PS --> MA: Status und Verordnungsdaten
deactivate PS

@enduml