@startuml

!procedure $tech_state_draft($alias)
state "draft" as $alias
!endprocedure


!procedure $tech_state_ready($alias)
state "ready" as $alias #Aquamarine
!endprocedure


!procedure $tech_state_in_progress($alias)
state "in-progress" as $alias #LimeGreen
!endprocedure


!procedure $tech_state_on_hold($alias)
state "on-hold" as $alias #OldLace
!endprocedure


!procedure $tech_state_completed($alias)
state "completed" as $alias #DodgerBlue
!endprocedure


!procedure $tech_state_cancelled($alias)
state "cancelled" as $alias #Orange
!endprocedure


!procedure $state_init($alias)
state "<<initialisiert>>\nOrderTask" as $alias
$alias : status = <b>draft</b>
$alias : businessStatus = <b>initialized</b>
!endprocedure

!procedure $state_open($alias)
state "<<offen>>\nOrderTask" as $alias #Aquamarine
$alias : status = <b>ready</b>
$alias : businessStatus = <b>open</b>
!endprocedure


!procedure $state_assigned($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #LimeGreen
$alias:status = <b>in-progress</b>
$alias:businessStatus = <b>assigned</b>
!endprocedure

!procedure $state_assigned_approved($alias)
state "<<zugewiesen (beschieden)>>\nOrderTask" as $alias #LimeGreen
$alias:status = <b>in-progress</b>
$alias:businessStatus = <b>assigned-approved</b>
!endprocedure

!procedure $state_review_from_open($alias)
state "<<offen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Antragsprüfung>></i>\n-Workflow" as sub_review_from_open #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>open</b> 
!endprocedure

!procedure $state_review_from_assigned($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Antragsprüfung>></i>\nWorkflow" as sub_review_from_assigned #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>assigned</b>
!endprocedure

!procedure $state_review_subworkflow($alias)
state "<<Antragsprüfung>>\nWorkflow" as $alias #SkyBlue {
}
!endprocedure


!procedure $state_correction($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Korrektur/Anfrage>></i>\nWorkflow" as sub_correction_from_review #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>assigned</b>
!endprocedure


!procedure $state_correction_open($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Korrektur/Anfrage>></i>\nWorkflow" as sub_correction_open_from_review #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>open</b>
!endprocedure


!procedure $state_review_correction($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Korrektur/Anfrage>></i>\nWorkflow" as sub_correction_from_review #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>assigned</b>
!endprocedure


!procedure $state_assigned_correction($alias)
state "<<zugewiesen>>\nOrderTask" as $alias #OldLace {
    state "<i><<Korrektur/Anfrage>></i>\nWorkflow" as sub_correction_from_assigned #Coral
}
$alias:status = <b>on-hold</b>
$alias:businessStatus = <b>assigned</b>
!endprocedure


!procedure $state_completed($alias)
state "<<abgeschlossen>>\nOrderTask" as $alias #DodgerBlue
$alias:status = <b>completed</b>
$alias:businessStatus = <b>completed</b>
!endprocedure

!procedure $state_deleted($alias)
state "<color:white>gelöscht" as $alias #Crimson
!endprocedure


!procedure $state_cancelled($alias)
state "<<gelöscht>>\nOrderTask" as $alias #Orange
$alias : status = <b>cancelled</b>
$alias : businessStatus = <b>deleted</b>
!endprocedure



' !procedure $state_reviewtask_requested($alias, $from)
' state "<<angefragt>>\nReviewTask" as $alias #BUSINESS
' $alias:status = <b>requested</b>
' $alias:businessStatus = <b>review-requested</b>
' $alias:invokesFromStatus = <b>$from</b>
' $alias:partOf = OrderTask
' !endprocedure


' !procedure $state_reviewtask_in_progress($alias, $from)
' state "<<in Durchführung>>\nReviewTask" as $alias #BUSINESS
' $alias:status = <b>in-progress</b>
' $alias:businessStatus = <b>review-in-progress</b>
' $alias:invokesFromStatus = <b>$from</b>
' $alias:partOf = OrderTask
' !endprocedure

' !procedure $state_reviewtask_completed($alias, $from)
' state "<<abgeschlossen>>\nReviewTask" as $alias #BUSINESS
' $alias:status = <b>in-completed</b>
' $alias:businessStatus = <b>review-completed</b>
' $alias:invokesFromStatus = <b>$from</b>
' $alias:partOf = OrderTask
' !endprocedure


!procedure $state_correction_requested($alias, $requestor, $owner)
state "<<Korrekturanfrage>>\n CorrectionFlowTask" as $alias #Coral
$alias:status = <b>requested</b>
$alias:businessStatus = <b>correction-requested</b>
$alias:requestor = <b>$requestor</b>
$alias:owner = <b>$owner</b>
$alias:partOf = OrderTask
!endprocedure


!procedure $state_correction_cancelled($alias, $requestor, $owner)
state "<<Korrekturanfrage storniert>>\n CorrectionFlowTask" as $alias #Coral
$alias:status = <b>cancelled</b>
$alias:businessStatus = <b>correction-cancelled</b>
$alias:requestor = <b>$requestor</b>
$alias:owner = <b>$owner</b>
$alias:partOf = OrderTask
!endprocedure


!procedure $state_correction_rejected($alias, $requestor, $owner)
state "<<Korrektur abgelehnt>>\n CorrectionFlowTask" as $alias #Coral
$alias:status = <b>rejected</b>
$alias:businessStatus = <b>correction-rejected</b>
$alias:requestor = <b>$requestor</b>
$alias:owner = <b>$owner</b>
$alias:partOf = OrderTask
!endprocedure


!procedure $state_correction_in_progress($alias, $requestor, $owner)
state "<<Korrektur in Bearbeitung>>\n CorrectionFlowTask" as $alias #Coral
$alias:status = <b>in-progress</b>
$alias:businessStatus = <b>correction-in-progress</b>
$alias:requestor = <b>$requestor</b>
$alias:owner = <b>$owner</b>
$alias:partOf = OrderTask
!endprocedure


!procedure $state_correction_completed($alias, $requestor, $owner)
state "<<Korrektur abgeschlossen>>\n CorrectionFlowTask" as $alias #Coral
$alias:status = <b>completed</b>
$alias:businessStatus = <b>correction-completed</b>
$alias:requestor = <b>$requestor</b>
$alias:owner = <b>$owner</b>
$alias:partOf = OrderTask
!endprocedure


!procedure $state_open_approved($alias)
state "<<offen>>\nOrderTask" as $alias #Aquamarine
$alias:status = <b>ready</b>
$alias:businessStatus = <b>open-approved</b>
!endprocedure

@enduml