@startuml

skinparam state {
  BackgroundColor Application
  BorderColor Black
  FontColor Black
  FontSize 22
  RoundCorner 0
  Shadowing false
  Margin 12
  MinimumWidth 260
  Padding 20
  
}

skinparam Arrow {
    FontSize 30
    FontStyle bold

}

skinparam json {
    BackgroundColor #1b678f
    BorderColor black
    FontColor white
    FontName Monospace
    FontSize 18
    RoundCorner 0
}

skinparam roundcorner 0

<style>
title {
  backgroundColor LightSteelBlue
  borderColor LightSteelBlue
  Padding 10
  FontColor Black
  HorizontalAlignment right
  FontSize 20
}
header {
  FontSize 14
  backgroundColor Teal
  borderColor Teal
  Padding 10
  HorizontalAlignment left
  Margin 0 0 30 0
}
</style>

@enduml