@startuml
title sd UC 3.9 - Dispensierinformationen durch Versicherte abrufen

actor Versicherter as V
participant "FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

V -> FdV : Dispensierinformationen abrufen()

FdV -> FD : GET /Dispensierinformationen ()

activate FD
FD -> FD : Zugriffsprotokoll erstellen()
FD --> FdV : {Dispensierinformationen,\nStatus, ...}
deactivate FD

FdV --> V : Status
@enduml
