@startuml
title sd UC 3.9 - Dispensierinformationen durch Versicherte abrufen

actor Versicherter as V
participant "FdV" as FdV
participant "E-Rezept-Fachdienst" as FD
participant "Identity Provider" as IDP

V -> FdV : Dispensierinformationen abrufen()

opt kein gültiger AuthN-Token
  ref over FdV, IDP: AuthN-Token anfordern
end

FdV -> FD : GET /Dispensierinformationen\n(AuthN-Token)

activate FD
FD -> FD : Zugriffsprotokoll erstellen()
FD --> FdV : {Dispensierinformationen,\nStatus, ...}
deactivate FD

FdV --> V : Status
@enduml
