@startuml
title UC 4.7 - Nachricht durch Abgebenden uebermitteln

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Antwortnachricht erstellen()
activate AVS

AVS -> FD: POST /Communication ()
activate FD
FD -> FD: Nachricht speichern()
FD --> AVS: Status
deactivate FD

AVS --> MA: Status
deactivate AVS

@enduml
