@startuml
title UC 4.7 - Nachricht durch Abgebenden uebermitteln

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "Identity Provider" as IDP
participant "E-Rezept-Fachdienst" as FD

MA -> AVS: Antwortnachricht erstellen()
activate AVS

opt kein gültiger AuthN-Token
  ref over AVS, IDP: AuthN-Token anfordern
end

AVS -> FD: POST /Communication (AuthN-Token, Antwort)
activate FD
FD -> FD: Nachricht speichern()
FD --> AVS: Status
deactivate FD

AVS --> MA: Status
deactivate AVS

@enduml
