@startuml
title UC 4.16 Dispensierinformationen durch Abgebenden bereitstellen

actor "Mitarbeiter LEI" as MA
participant "Primärsystem abgebende LEI" as PS
participant "TI-Flow-Fachdienst" as FD

MA -> PS : E-Rezept dispensieren()
MA -> PS : Dispensierinformationen bereitstellen()

activate PS
PS -> PS : MedicationDispense erstellen()
PS -> PS : Rezept-ID und Secret des E-Rezepts bestimmen()

PS -> FD : POST /Task/{id}/$dispense (Secret, MedicationDispense)
activate FD
FD -> FD: Secret prüfen()
FD -> FD: Status Task prüfen()
FD -> FD : MedicationDispense speichern()
FD -> FD : Referenz zur MedicationDispense im Task speichern()
FD -> FD : Zeitstempel der Abgabeinformationen setzen(aktuelleZeit())
FD -> FD : Datenzugriff protokollieren()

FD --> PS : Status, Dispensierinformation
deactivate FD

PS --> MA : Status
deactivate PS

@enduml
