@startuml
title UC 4.2 - E-Rezept durch Abgebenden zurückgeben

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "Identity Provider" as IDP
participant "E-Rezept-Fachdienst" as FD

MA -> AVS: E-Rezept zurückgeben()
activate AVS

opt kein gültiger AuthN-Token
  ref over AVS, IDP: AuthN-Token anfordern
end

AVS -> FD: POST /Task/{id}/$reject (AuthN-Token, Secret)
activate FD
FD -> FD: Status auf "offen" setzen()
FD -> FD : Datenzugriff protokollieren()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Token und Secret löschen()
AVS --> MA: Status
deactivate AVS

@enduml
