@startuml
title UC 4.3 - E-Rezept durch Abgebenden löschen

actor "Mitarbeiter Apotheke" as MA
participant "AVS" as AVS
participant "Identity Provider" as IDP
participant "E-Rezept-Fachdienst" as FD

MA -> AVS: E-Rezept löschen()
activate AVS

opt kein gültiger AuthN-Token
  ref over AVS, IDP: AuthN-Token anfordern
end

AVS -> FD: POST /Task/{id}/$abort (AuthN-Token, Secret)
activate FD
FD -> FD: Status auf "gelöscht" setzen()
FD -> FD: Daten löschen()
FD -> FD : Datenzugriff protokollieren()
FD --> AVS: Status
deactivate FD

AVS -> AVS: Token und Secret löschen()
AVS --> MA: Status
deactivate AVS

@enduml
