@startuml 
title UC 3.14 - Einwilligung durch den Versicherten erteilen

autonumber "<b>[0]"
actor "Versicherte" as Ver
participant "E-Rezept-FdV" as FdV
participant "TI-Flow-Fachdienst" as FD

Ver -> FdV: Einwilligung erteilen
FdV -> FD: POST /Consent (category)
FD -> FD: Einwilligung speichern
FD -> FD: Datenzugriff protokollieren
FD --> FdV: :Consent
FdV --> Ver: Status

@enduml  