@startuml 
title Ablaufdiagramm Verordnung von DiGA
hide footbox
autonumber "<b>[0]"
actor "Verordnender" as VERO
participant "PVS" as PVS
participant "FdV" as FDV
participant "TI-Flow-Fachdienst" as FD
participant "FHIR Verzeichnisdienst" as VZD
participant "Kostenträger-Clientsystem" as KTR

    VERO -> PVS: Verordnungsdatensaetze auswählen
    PVS -> FD: Workflow erstellen\nmit $Create (Workflow 162)
    PVS -> PVS: Verordnungsdatensatz\nerstellen
    
    VERO -> PVS: QES auslösen()
    PVS -> PVS: Verordnungsdatensatz\nmit QES signieren 
    PVS --> VERO: Signierte Verordnung
    
    VERO -> PVS: Verordnung zum Einstellen auswählen
	PVS -> FD: Einstellen der \nVerordnung mit $activate
    FD -> FD: QES und FHIR prüfen
    PVS -> VERO: Verordnung eingestellt
    
    FDV -> FD: Abruf der Verordnungen\nmit GET /Task


	FDV <-> VZD: Falls nicht bekannt: Zieladresse für Zuweisung durch Lookup der\nTelematik-ID des Kostenträgers  ermitteln\n(auf Basis Authentisierungsinformationen des Nutzers)
    FDV -> FDV: Communication Ressource\nfür Zuweisen erstellen
    FDV -> FD: POST /Communication 

	KTR <- FD: WebSocket-Signal neue Communication\nmit "Zuweisung DiGA-Verordnung"

    KTR -> FD: GET /Communication 	
    KTR -> FD: Abruf der Verordnung mit $accept\n(Task-ID und AccessCode\naus Communication)
 
alt Erfolgreiche Bearbeitung des E-Rezepts
    KTR -> KTR: Freischaltcode erzeugen
	
	KTR -> FD: $close (Freischaltcode \nin Dispensierinformation enthalten)
    FDV <- FD: Abruf Dispensierinformation
    FDV -> FDV: Verwendung Freischaltcode\nmit DiGA

    KTR -> KTR: die weitere Verarbeitung\ninklusiver Abrechnung\nerfolgt in Kassenhoheit\nmit den DiGA-Anbietern
else E-Rezept wird zurückgegeben
    KTR -> KTR: Prüfung ergibt Rückgabe des E-Rezeptes
    KTR -> FD: $reject (Rückgabe der Verordnung\nan den TI-Flow-Fachdienst)
	
	KTR -> FD: POST /Communication mit\nRückgabegrund als Freitext
    FDV -> FDV: Darstellung des Rückgabegrundes an den Versicherten
end
@enduml