@startuml
title Verordnungsdatensatz qualifiziert signieren

actor "Verordnender" as VERO
participant "PVS" as PVS
participant "Konnektor" as K

VERO -> PVS: QES auslösen()
activate PVS

PVS -> K: sign_Document_QES(Verordnungsdatensatz)
activate K
K --> PVS: QES-Signatur
deactivate K

PVS -> PVS: Signierten Verordnungsdatensatz speichern()
PVS --> VERO: QES abgeschlossen
deactivate PVS

@enduml
