@startuml
title UC 4.8 - Quittung erneut abrufen

actor "Mitarbeiter KTR" as MA
participant "Clientsystem\nKostenträger" as AVS
participant "TI-Flow-Fachdienst" as FD

MA -> AVS: Quittung erneut abrufen()
activate AVS

AVS -> FD: GET /Task/{id} (Secret)
activate FD
FD -> FD: Secret prüfen()
FD -> FD: Telematik-ID prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Quittung erneut bereitstellen()
FD --> AVS: Quittung
deactivate FD

AVS --> MA: Quittung
deactivate AVS

@enduml
