@startuml
title UC 4.6 - Nachrichten durch Abgebenden empfangen

actor "Mitarbeiter KTR" as MA
participant "Clientsystem\nKostenträger" as KTR
participant "TI-Flow-Fachdienst" as FD

MA -> KTR: E-Rezept-Token empfangen()
activate KTR

KTR -> FD: GET /Communication ()
activate FD
FD -> FD: Nachrichten ermitteln()
FD --> KTR: E-Rezept-Token
deactivate FD


KTR --> MA: Token verfügbar
deactivate KTR

@enduml
