@startumlz
title UC 2.1 - Verordnung erzeugen

actor "Verordnender" as VERO
participant "PVS" as PVS
participant "TI-Flow-Fachdienst" as FD
participant "Konnektor" as K

VERO -> PVS: Verordnungsdatensaetze auswählen()
activate PVS

PVS -> FD: POST /Task/$create (FlowType)
activate FD
FD -> FD: Task erzeugen()
FD -> FD: Rezept-ID erzeugen()
FD -> FD: AccessCode erzeugen()
FD --> PVS: Task, Rezept-ID, AccessCode
deactivate FD

PVS -> PVS: AccessCode speichern()
PVS -> PVS: Rezept-ID in Verordnungsdatensatz ergänzen()

ref over PVS, K: Verordnungdatensatz qualifiziert signieren

PVS --> VERO: Signierte Verordnung
deactivate PVS

@enduml
