@startuml
title Verordnung qualifiziert signieren

actor "Verordnender" as V
participant "Primärsystem" as PS
participant "Konnektor" as K

V -> PS: QES auslösen()
activate PS

PS -> K: sign_Document_QES(Verordnungsdatensatz)
activate K
K --> PS: QES-Signatur
deactivate K

PS -> PS: Signierten Verordnungsdatensatz speichern()
PS --> V: QES abgeschlossen
deactivate PS

@enduml
