@startuml
title UC 2.5 - Verordnung durch Verordnenden löschen

actor "Verordnender" as VERO
participant "PVS" as PVS
participant "TI-Flow-Fachdienst" as FD

VERO -> PVS: Verordnung zum Löschen markieren()
activate PVS

PVS -> FD: POST /Task/{id}/$abort (AccessCode)
activate FD
FD -> FD: AccessCode prüfen()
FD -> FD: Status auf "cancelled" setzen()
FD -> FD: Personenbezogene Daten löschen()
FD --> PVS: Status
deactivate FD

PVS -> PVS: AccessCode löschen()
PVS --> VERO: Status
deactivate PVS

@enduml
