@startuml
title UC 2.3 - Verordnung einstellen

actor "(Zahn-)Arzt / Psychotherapeuten" as Arzt
participant "Primärsystem" as PS
participant "TI-Flow-Fachdienst" as FD

Arzt -> PS: Verordnung zum Einstellen auswählen()
activate PS

PS -> FD: POST /Task/{id}/$activate (AccessCode, QES-Bundle)
activate FD
FD -> FD: AccessCode prüfen()
FD -> FD: Signatur und Daten prüfen()
FD -> FD: Status auf "ready" setzen()
FD --> PS: Status, Verordnung aktualisiert
deactivate FD

PS -> PS: E-Rezept-Token erstellen()
PS --> Arzt: Verordnung eingestellt
deactivate PS

@enduml
