@startuml
title UC 2.3 - Verordnung einstellen

actor "Verordnender" as VERO
participant "PVS" as PVS
participant "TI-Flow-Fachdienst" as FD

VERO -> PVS: Verordnung zum Einstellen auswählen()
activate PVS

PVS -> FD: POST /Task/{id}/$activate (AccessCode, QES-Bundle)
activate FD
FD -> FD: AccessCode prüfen()
FD -> FD: Status Task prüfen()
FD -> FD: Signatur und Daten prüfen()
FD -> FD: Status auf "ready" setzen()
FD --> PVS: Status, Verordnung aktualisiert
deactivate FD

PVS -> PVS: E-Rezept-Token erstellen()
PVS --> VERO: Verordnung eingestellt
deactivate PVS

@enduml
